services:
  db:
    image: postgres:14
    container_name: tp2_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # opcional: conectar desde el host con un cliente externo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  app-qa:
    image: agustinreynaucc/tp2-flask:dev   # tu imagen publicada en Docker Hub
    container_name: tp2_app_qa
    restart: unless-stopped
    env_file: .env.qa
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5000"   # afuera 5001 → adentro 5000

  app-prod:
    image: agustinreynaucc/tp2-flask:v1.0   # MISMA IMAGEN
    container_name: tp2_app_prod
    restart: unless-stopped
    env_file: .env.prod
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5002:5000"   # PROD afuera 5002 → adentro 5000

volumes:
  dbdata: